"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

format = """
$username\
$hostname\
$directory\
$aws\
$git_branch\
$git_state\
$git_status\
$conda\
$python
$character
"""

add_newline = true
palette = 'nord'

[palettes.nord]
nord0 = '#2E3440'
nord1 = '#3B4252'
nord2 = '#434C5E'
nord3 = '#4C566A'
nord4 = '#D8DEE9'
nord5 = '#E5E9F0'
nord6 = '#ECEFF4'
nord7 = '#8FBCBB'
nord8 = '#88C0D0'
nord9 = '#81A1C1'
nord10 = '#5E81AC'
nord11 = '#BF616A'
nord12 = '#D08770'
nord13 = '#EBCB8B'
nord14 = '#A3BE8C'
nord15 = '#B48EAD'

[username]
style_root = 'nord8 bold'
style_user = 'nord8'
format = '[ $user@]($style)'
show_always = true

[hostname]
ssh_only = false
format = '[$hostname]($style)'
style = 'nord8'

[directory]
truncation_length = 5
truncate_to_repo = false
format = '  [󰉖 $path]($style)'
style = 'nord9'

[aws]
format = '  [$symbol( $profile)]($style)'
symbol = ' '
style = 'nord10'

[git_branch]
format = '  [$symbol$branch(:$remote_branch)]($style)'
symbol = ''
style = 'nord10'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = 'nord10'

[git_status]
format = '[\[$all_status$ahead_behind\]]($style)'
style = 'nord10'

[conda]
format = '  [$symbol$environment]($style)'
symbol = '󰯳 '
ignore_base = false
style = 'nord10'

[python]
format = '  [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = '󰌠 '
style = 'nord10'

[character]
success_symbol = '[](nord6)'
error_symbol = '[](nord6)'
vimcmd_symbol = '[](nord6)'
vimcmd_replace_one_symbol = '[](nord6)'
vimcmd_replace_symbol = '[](nord6)'
vimcmd_visual_symbol = '[](nord6)'
